### ISSUE TITLE
SQL injections are possible when using partition string_firstchars (Postgres, Django)

### ISSUE THREAD

**Issue by schumannd** [maxtepkeev/architect#14]
`SUBSTR(LOWER(NEW.<column_name>), 1, <n>)` is used in the trigger function. If the column value contains special characters it breaks. And if you chose n large enough SQL injections become possible. We fixed this using:
```SUBSTR(LOWER(regexp_replace(NEW.<column_name>, '[^a-zA-Z]', '', 'g')), 1, <n>);```
Which makes everything much more stable

**Comment by maxtepkeev** [comment]
So basically, you're proposing to remove everything except letters. I don't think this is a good idea, because I may want to use any characters in my strings and this is a perfectly legal use case.

Also, can you suggest an example that will break this function ?

**Comment by schumannd** [comment]
You are right, this was tailored to my specific usecase.
IIRC this line broke when using certain special chars like ';'

"match := LOWER(SUBSTRING(NEW.{{column}} FROM '.{{{{{constraint}}}}}$'));",
"tablename := '{{parent_table}}_' || match;"

**Comment by maxtepkeev** [comment]
I was able to reproduce it, the fix will be introduced in the next version. Thanks for your time and help.

**Comment by maxtepkeev** [comment]
Fixed in v0.5.2
