### ISSUE TITLE
Django Translations getting in the way

### ISSUE THREAD

**Issue by Archarachne** [maxtepkeev/architect#21]
Hi!

I tried to use architect but I encountered a problem I don't really know how to handle.
I described it here: http://stackoverflow.com/questions/33260386/partitioning-django-with-architect-package-translation-error

I don't know if it is the Architect issue or my lack of knowledge how to handle Django, but if you could help me on the subject I would be grateful.

**Comment by maxtepkeev** [comment]
Hi!

Can you please provide me with the example of the code you're using, so I could reproduce your error here, thanks.

**Comment by Archarachne** [comment]
I cannot provide you with the original code unfortunatelly (it's from my work), but if you could maybe try create a Model with a field using:

from django.utils.translation import ugettext as _

class Model(models.Model):
    uuid = models.CharField(_("Model ID"), null=False, max_length=32)

And then run the architect partition command.
It should throw the error I've provided you with on stackoverflow.

**Comment by maxtepkeev** [comment]
I'm getting the same error with your code, but switching to ``ugettext_lazy`` resolves this issue for me, so you can use this for now. I don't have much time to investigate this right now, but I'll try to do this on weekend. So for now you can use ``ugettext_lazy``. After I'll get more info, I'll post a reply here.

**Comment by Archarachne** [comment]
Thanks, that would be great! The project is huge and now I have to work my way on it to switch to lazy translations, but some where done like that for a reason. I'll be watching this issue.

**Comment by maxtepkeev** [comment]
Fixed in v0.5.3
