### ISSUE TITLE
Use Django DB Routers to determine the correct database for a model

### ISSUE THREAD

**Issue by lig** [maxtepkeev/architect#30]
Django ConnectionMixin supports DEFAULT_DB_ALIAS only. https://github.com/maxtepkeev/architect/blob/master/architect/orms/django/features.py#L20

There should be support for multi db Django configuration https://docs.djangoproject.com/en/1.9/topics/db/multi-db/

**Comment by maxtepkeev** [comment]
Architect supports multi databases in Django, see [docs](http://architect.readthedocs.io/features/partition/index.html#table-partitioning), specifically the ``db`` options where you need to set the connection name used for this model. DEFAULT_DB_ALIAS is used when ``db`` option isn't set.

**Comment by lig** [comment]
Thank you for the clarification. I will try that option.

**Comment by lig** [comment]
However, it looks like using django db router to determine the correct DB Alias for the Model by default will be much more handy.

**Comment by maxtepkeev** [comment]
Agree, however this isn't implemented at the moment, so we'll keep this issue open until I have time to do that or somebody will make a pull request.

**Comment by maxtepkeev** [comment]
Added in v0.5.4.
