### ISSUE TITLE
Error while trying to run architect partition --module my_app.models

### ISSUE THREAD

**Issue by limitScreen** [maxtepkeev/architect#33]
Hi,
Running this:
$ architect partition --module myapp.models

And getting this error:

django.db.utils.ProgrammingError: invalid type name "myapp_modelname."reportingdteonly"%TYPE"
LINE 6:                     match myapp_modelname."reportingdteonly"...
                                  ^

the reportingdteonly is of type Datetime

DB postgres 9.4
Really appreciate your help here

**Comment by maxtepkeev** [comment]
Hi,

I don't think there is a problem with architect somewhere, also there was already a similar issue, see #28. Maybe you also have the same problem with inheritance somewhere.

If you won't be able to figure it out by yourself, that I will need to see your exact code with model and all the inheritance models too.

**Comment by maxtepkeev** [comment]
Closing this due to the lack of activity. If you still need help please let me know and I'll reopen this issue.
