### ISSUE TITLE
How to SELECT from partitions with ORM?

### ISSUE THREAD

**Issue by Hukuta** [maxtepkeev/architect#34]
I have a Django model like this:

```
@architect.install('partition', type='range', subtype='integer', constraint='100', column='search_id')
class SearchResult(models.Model):
    search = models.ForeignKey(Search, on_delete=models.CASCADE)
    ...
```

When I am selecting with ORM filtering by partition column 

`SearchResult.objects.filter(search_id=3502).only('id').first()`

Django selects from master table:

> (0.005) SELECT "app_searchresult"."id" FROM "app_searchresult" WHERE "app_searchresultapp_searchresult"."search_id" = 3502 ORDER BY "app_searchresult"."id" ASC LIMIT 1; args=(3502,)

How I can select something with ORM from tables caled like "app_searchresult_3501_3600"?
I believe that I don't need to know a table name for this.

**Comment by maxtepkeev** [comment]
With table partitioning you just select from the master table as you do without partitioning, database takes care about which partition to query for you. That's the whole point of partitioning. You don't need to know which partition to query for a specific record.

**Comment by Hukuta** [comment]
So when query like this:
`SearchResult.objects.first()`
Db is looking only in "app_searchresult" table?
And when  
`SearchResult.objects.filter(search_id__in=[1, 3502]).first())`
it's looking in join "app_searchresult_3501_3600" and "app_searchresult_1_100" ?
or in  "app_searchresult" table again?

And when 
`SearchResult.objects.filter(search_id__in=[3501, 3502]).first())`
only in  "app_searchresult_3501_3600" ?

**Comment by maxtepkeev** [comment]
No, it's more complicated than that and it depends on how Django constructs underlying query. This is a big topic, if you want to know low-level details please have a look at the PostgreSQL [docs for partitioning](https://www.postgresql.org/docs/current/static/ddl-partitioning.html). Also you're using the foreign key for partitioning, that is a bad idea with PostgreSQL, see https://github.com/maxtepkeev/architect/issues/27#issuecomment-201199472 for details.

**Comment by Hukuta** [comment]
thanks
