### ISSUE TITLE
Partitioning by field "end" causes ProgrammingError when trying to insert new row

### ISSUE THREAD

**Issue by ra2er** [maxtepkeev/architect#35]
ProgrammingError: record "new" has no field "end"
LINE 1: SELECT NEW.end IS NULL
               ^
QUERY:  SELECT NEW.end IS NULL
CONTEXT:  PL/pgSQL function test_table_insert_child() line 8 at IF

**Comment by maxtepkeev** [comment]
Fixed by #36

**Comment by ra2er** [comment]
Can you update on pypi? Thanks for quick update.

**Comment by maxtepkeev** [comment]
For sure I will, just need to check for a few more things + travis-ci limited their job matrix to 200 jobs only, so I have to simplify travis-ci.yml to make tests work again, it will take some time, so can't promise you a release today, but for sure tomorrow. Will post here when I'm done.

**Comment by maxtepkeev** [comment]
@ra2er v0.5.6 with the fix is on PyPI. Apologies for the delay.
