### ISSUE TITLE
Invalid type name on architect partition --module myapp.models

### ISSUE THREAD

**Issue by agultekin** [maxtepkeev/architect#58]
Hi,
I saw a similar issue about this problem but I don't have the same configuration:
If the app name is uppercase and you want to execute the command architect, you will have the error invalid type name.
To correct this I changed in architect/databases/postgresql/partition.py the PSQL code.

`
return self.database.execute("""
                    -- We need to create a before insert function
                    CREATE OR REPLACE FUNCTION {{parent_table}}_insert_child()
                    RETURNS TRIGGER AS $$
                        DECLARE
                            match {{parent_table_origin}}.{{column}}%TYPE;
                            tablename VARCHAR;
                            checks TEXT;
                            {declarations}
                        BEGIN
                            IF NEW.{{column}} IS NULL THEN
                                tablename := '{{parent_table}}_null';
                                checks := '{{column}} IS NULL';
                            ELSE
                                {variables}
                            END IF;

                            IF NOT EXISTS(
                                SELECT 1 FROM information_schema.tables WHERE table_name=tablename)
                            THEN
                                BEGIN
                                    EXECUTE 'CREATE TABLE ' || tablename || ' (
                                        CHECK (' || checks || '),
                                        LIKE "{{parent_table}}" INCLUDING DEFAULTS INCLUDING CONSTRAINTS INCLUDING INDEXES
                                    ) INHERITS ("{{parent_table}}");';
                                EXCEPTION WHEN duplicate_table THEN
                                    -- pass
                                END;
                            END IF;

                            EXECUTE 'INSERT INTO ' || tablename || ' VALUES (($1).*);' USING NEW;
                            RETURN NEW;
                        END;
                    $$ LANGUAGE plpgsql;

                    -- Then we create a trigger which calls the before insert function
                    DO $$
                    BEGIN
                    IF NOT EXISTS(
                        SELECT 1
                        FROM information_schema.triggers
                        WHERE event_object_table = '{{parent_table}}'
                        AND trigger_name = 'before_insert_{{parent_table_lowcase}}_trigger'
                    ) THEN
                        CREATE TRIGGER before_insert_{{parent_table}}_trigger
                            BEFORE INSERT ON "{{parent_table}}"
                            FOR EACH ROW EXECUTE PROCEDURE {{parent_table}}_insert_child();
                    END IF;
                    END $$;

                    -- Then we create a function to delete duplicate row from the master table after insert
                    CREATE OR REPLACE FUNCTION {{parent_table}}_delete_master()
                    RETURNS TRIGGER AS $$
                        BEGIN
                            DELETE FROM ONLY "{{parent_table}}" WHERE {{pk}};
                            RETURN NEW;
                        END;
                    $$ LANGUAGE plpgsql;

                    -- Lastly we create the after insert trigger that calls the after insert function
                    DO $$
                    BEGIN
                    IF NOT EXISTS(
                        SELECT 1
                        FROM information_schema.triggers
                        WHERE event_object_table = '{{parent_table}}'
                        AND trigger_name = 'after_insert_{{parent_table_lowcase}}_trigger'
                    ) THEN
                        CREATE TRIGGER after_insert_{{parent_table}}_trigger
                            AFTER INSERT ON "{{parent_table}}"
                            FOR EACH ROW EXECUTE PROCEDURE {{parent_table}}_delete_master();
                    END IF;
                    END $$;
                """.format(**definitions).format(
            pk=' AND '.join('{pk} = NEW.{pk}'.format(pk=pk) for pk in self.pks),
            parent_table=self.table,
            parent_table_lowcase=str(self.table).lower(),
            parent_table_origin='"{0}"'.format(self.table),
            column='{0}'.format(self.column_name)
        ))`
As I use only Postgresql, I couldn't do any other tests for others db.

**Comment by agultekin** [comment]
Hi,
Firstable thank you for the correction.
I tested the correction and it fails! 

I replaced the following line : 
` match {{parent_table}}.{{column}}%TYPE;`
by
` match "{{parent_table}}".{{column}}%TYPE;`
and it worked.

**Comment by CchOOlak** [comment]
Hi bros.
You can try migrate your new database.
Good Luck.

**Comment by maxtepkeev** [comment]
Fixed in 0.6.0
