### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by cristianocca** [maxtepkeev/architect#69]
Is this still maintained? Alternatives?

**Comment by Andrew-Chen-Wang** [comment]
@cristianocca @utapyngo @orrion Not maintained, but I just filed #71 and it seems to still work considering ORMs don't typically recreate their ORMs. In that issue, I show how to do rework Travis to make sure your configuration works. (For Django and Python 3.4 and MySQL, it will not work. This happens in all repositories that test MySQL with Python 3.4 and Django; however PostgreSQL works fine in all Py versions).

**Comment by maxtepkeev** [comment]
Support for all latest ORM versions and Python versions has been added in 0.6.0, but if someone wants to contribute you're more than welcome as I'm having really hard time to find free time for further active development.
